apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: ImagePolicyWebhook
  configuration:
    imagePolicy:
      kubeConfigFile: /etc/kubernetes/image-policy/image-policy-webhook.conf
      allowTTL: 50
      denyTTL: 50
      retryBackoff: 500
      defaultAllow: true
